export const ERC20_ABI = [
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function allowance(address owner, address spender) external view returns (uint256)',
  'function balanceOf(address account) external view returns (uint256)',
  'function transfer(address to, uint256 amount) external returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) external returns (bool)',
  'function decimals() external view returns (uint8)',
];

export const ESCROW_ABI = [
  'function createOrder(string memory _orderId, address _seller, uint256 _amount, address _paymentToken) external',
  'function agreeToOrder(string memory _orderId) external',
  'function fundOrder(string memory _orderId) external',
  'function markAsShipped(string memory _orderId) external',
  'function confirmDelivery(string memory _orderId) external',
  'function releaseFunds(string memory _orderId) external',
  'function autoReleaseFunds(string memory _orderId) external',
  'function raiseDispute(string memory _orderId) external',
  'function resolveDispute(string memory _orderId, bool _favorBuyer) external',
  'function cancelOrder(string memory _orderId) external',
  'function getOrder(string memory _orderId) external view returns (tuple(string orderId, address buyer, address seller, uint256 amount, uint256 sellerHoldAmount, address paymentToken, uint8 status, uint256 createdAt, uint256 deliveryDeadline, bool buyerConfirmed, bool sellerConfirmed, bool sellerAgreed))',
  'function platformFeePercent() external view returns (uint256)',
  'function nonGhettoFeeAddition() external view returns (uint256)',
  'function sellerHoldPercent() external view returns (uint256)',
  'function REQUIRED_GHETTO_COLLATERAL() external view returns (uint256)',
  'function setPlatformFee(uint256 _feePercent) external',
  'function setNonGhettoFeeAddition(uint256 _feeAddition) external',
  'function setSellerHoldPercent(uint256 _holdPercent) external',
  'function sellerBalances(address seller, address token) external view returns (uint256)',
  'function sellerGhettoCollateral(address seller) external view returns (uint256)',
  'function sellerHeldFunds(address seller) external view returns (uint256)',
  'function getAvailableCollateral(address seller) external view returns (uint256)',
  'function depositGhettoCollateral(uint256 amount) external',
  'function withdrawGhettoCollateral(uint256 amount) external',
  'function withdrawSellerBalance(address token) external',
  'function calculateTotalFee(address paymentToken, uint256 amount) external view returns (uint256)',
  'function owner() external view returns (address)',
  'event OrderCreated(string indexed orderId, address indexed buyer, address indexed seller, uint256 amount, address paymentToken)',
  'event OrderFunded(string indexed orderId, uint256 amount, address paymentToken)',
  'event OrderShipped(string indexed orderId)',
  'event OrderDelivered(string indexed orderId)',
  'event OrderCompleted(string indexed orderId)',
  'event OrderDisputed(string indexed orderId)',
  'event OrderCancelled(string indexed orderId)',
  'event FundsReleased(string indexed orderId, address indexed seller, uint256 amount, address token)',
];

export const GHETTO_TOKEN_ABI = [
  'function name() external view returns (string)',
  'function symbol() external view returns (string)',
  'function decimals() external view returns (uint8)',
  'function totalSupply() external view returns (uint256)',
  'function balanceOf(address account) external view returns (uint256)',
  'function transfer(address to, uint256 amount) external returns (bool)',
  'function allowance(address owner, address spender) external view returns (uint256)',
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) external returns (bool)',
  'function externalTransfersAllowed() external view returns (bool)',
  'function blacklisted(address account) external view returns (bool)',
  'function marketplaceContracts(address contractAddress) external view returns (bool)',
  'function setBlacklisted(address account, bool _blacklisted) external',
  'function setMarketplaceContract(address contractAddress, bool whitelisted) external',
  'function setExternalTransfersAllowed(bool allowed) external',
  'function mint(address to, uint256 amount) external',
  'function burn(uint256 amount) external',
  'function burnFrom(address account, uint256 amount) external',
  'function pause() external',
  'function unpause() external',
  'function paused() external view returns (bool)',
  'function owner() external view returns (address)',
  'function getTokenInfo() external view returns (string, string, uint8, uint256, bool)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
  'event AddressBlacklisted(address indexed account, bool blacklisted)',
  'event MarketplaceContractUpdated(address indexed contractAddress, bool whitelisted)',
  'event ExternalTransfersToggled(bool allowed)',
];
